Increments123
evgenv123/go-shortener pull request #1
Opened 2021-09-02 18:51 UTC by evgenv123

код инкрементов 1, 2 и 3

2021-09-03 18:01 UTC, iTiky requested changes
Требуются минорные доработки по коду.

2021-09-04 10:19 UTC, evgenv123 commented on cmd/shortener/main.go
> +	r.Get("/{id}", app.MyHandler)
исправлено

2021-09-04 10:20 UTC, evgenv123 commented on internal/app/app.go
> +	switch {
исправлено

2021-09-04 10:20 UTC, evgenv123 commented on internal/app/app.go
> +			log.Fatal(err)
исправлено везде

2021-09-04 10:21 UTC, evgenv123 commented on internal/app/app.go
> +		m[idForLink] = string(b)
Добавлена проверка валидности через url.ParseRequestURI

2021-09-04 10:21 UTC, evgenv123 commented on internal/app/app_test.go
> +	tests := []struct {
Добавлен тест func TestHappyPath(t *testing.T)

2021-09-05 16:40 UTC, iTiky approved these changes
👍 Мелкое пожелание по тестам: happy path не должен сильно выделяться по стилю от других тестов, т.е. это должен быть "еще один" test case среди остальных.

2021-09-06 02:58 UTC, merged