Increments4567
evgenv123/go-shortener pull request #2
Opened 2021-09-11 06:19 UTC by evgenv123

2021-09-12 15:03 UTC, iTiky requested changes
Требуется доработка. В коде есть критическая недоработка (возможная паника). Большинство комментариев направлены на приведение кода к Go-way стилю оформления.

2021-09-18 04:42 UTC, evgenv123 commented on internal/config/config.go
> +var (
1. Добавлен глобальный объект Config в модуле config
2. Добавлен метод Config.Validate(), вызывается из main.init()

2021-09-18 04:44 UTC, evgenv123 commented on internal/config/config.go
> +func getEnv(key string, defaultVal string) string {
Задействовал пакеты github.com/caarlos0/env и github.com/alexflint/go-arg чтобы все считывалось сразу в структуру 

> Config

2021-09-18 04:48 UTC, evgenv123 commented on internal/config/config.go
> +func InitEnv() {
учтено

2021-09-18 05:07 UTC, evgenv123 commented on cmd/shortener/main.go
> +func init() {
Учитывая что при ошибке в стартовых параметрах программа не должна стартовать - вообще отказался от `func init()`

2021-09-18 05:46 UTC, evgenv123 commented on cmd/shortener/main.go
> +	log.Fatal(http.ListenAndServe(config.ServerAddr, r))
исправлено

2021-09-18 06:19 UTC, evgenv123 commented on internal/app/app.go
> +	defer dataFile.Close()
Исправлено

2021-09-18 06:23 UTC, evgenv123 commented on internal/app/app.go
> +	dataEncoder.Encode(DB)
исправлено

2021-09-18 07:31 UTC, evgenv123 commented on internal/app/app.go
> +type ShortenedURLs struct {
Добавлен файл `internal/app/definitions.go`

2021-09-18 07:35 UTC, evgenv123 commented on internal/app/app.go
> +	DB.URLMap[idForLink] = url
В структуру `ShortenedURLs `добавлен объект `sync.RWMutex`

2021-09-18 07:36 UTC, evgenv123 commented on internal/app/app.go
> +	return OutputShortURL{Result: config.BaseURL + "/" + strconv.Itoa(idForLink)}
исправлено там где длинные `return`

2021-09-18 07:38 UTC, evgenv123 commented on internal/app/app.go
> +		fmt.Println(err)
Исправлено

2021-09-18 07:53 UTC, evgenv123 commented on internal/app/app.go
> +		return
добавлено прокидывание наверх ошибки и обработка на уровне `func main()` (для `func readDBFromFile(filename string) error`)
И обработка на уровне `HandlerFunc` для `func writeDBToFile() error`

2021-09-18 08:39 UTC, evgenv123 commented on internal/app/app.go
> +		fmt.Println(err)
Добавлено прокидывание ошибки и обработка на уровне `func Init(c config.Config) error` в модуле `app`

2021-09-20 11:29 UTC, iTiky approved these changes
👍 Все замечания учтены, работа принята. Оставил мелкий коммент по Go-style. Еще отмечу, что лучше придерживаться единого стиля написания кода: в некоторых местах `return` отделен пустой строкой, где-то нет.

2021-09-20 11:29 UTC, iTiky commented on internal/app/definitions.go
> +	mu     sync.RWMutex
В Go принято использовать struct embedding для мьютекса, т.е.:
```go
type ShortenedURLs struct {
 	sync.RWMutex

 	URLMap map[int]string
}
```

Тогда операции Lock/Unlock будут выглядеть так:
```go
s := ShortenedURLs{}
s.RLock()
defer s.RUnlock()
```

2021-09-20 17:08 UTC, evgenv123 commented on internal/app/definitions.go
> +	mu     sync.RWMutex
исправлено

2021-09-20 17:08 UTC, merged